### ISSUE TITLE
passing graph durations

### ISSUE THREAD

**Issue by pycode122** [mattykay/pybix#7]
I'm trying to pass custom time frame as below but i would see response  graphs contains past hour data as per pybix default values.

is there an issue in my way of passing values.

def main(hostid):
    data = graphs(hostid)
    _current = datetime.datetime.now()
    _from = _current - datetime.timedelta(30)
    print(_from,_current)
    for d in data:
        graph.get_by_graph_id(d['graphid'],_current,_from)

if __name__ == "__main__":
    hostid = int(sys.argv[1])
    main(hostid)

**Comment by pycode122** [comment]
even im trying as below....


    _current = datetime.datetime.now()
    _from = _current - datetime.timedelta(30)
    
    _current = _current.strftime('%Y%m%d-%H%M%S')
    _from = _from.strftime('%Y%m%d-%H%M%S')

still i'm getting past hour data

**Comment by mattykay** [comment]
Thanks for the report pycode122 (sorry didn't see this till now)

There's a couple of issues here.

1. I haven't documented the Zabbix-supported date formats or added support for datetime objects.

    * Zabbix >v4 only supports formats in '%Y-%m-%d %H:%M:%S' or 'now-x' (where x is a supported value like month: '6M', day: '1d', year '1y'). The easiest way to see what will work at the moment, is to play around with the dates selector in the "Monitoring > Graphs" section as the "from" & "to" fields are literally what gets passed as-is currently. However, this is something that ideally should be validated via Pybix - as you've probably noticed that there's no error, just an image response by Zabbix with the error text in the image.

2. You have the from_date/to_date's back to front, so Zabbix errors with "Zabbix has recieved an incorrect Request. Minimum time period to display is 1 minute"

```
graph.get_by_graph_id(d['graphid'],_from,_current)
graph.get_by_graph_id(graph_id=d['graphid'],from_date=_from,to_date=_current) # e.g. with kwargs
```

3. When using the supported date format '%Y-%m-%d %H:%M:%S', until commit af86338, it wasn't possible to save file since it contains unsupported filename characters like ':' - the commit noted "fixes" this by removing it from file name, but ideally unit testing and increased date support is the actual solution.

**Future work**
* Document and validate supported input times
* Handle datetime objects
* Increased unit testing
